### ISSUE TITLE
traíra

### ISSUE THREAD

**Issue by ABNERMATHEUS** [tchars/Gympassly#1]

**Comment by ABNERMATHEUS** [comment]
Quer fazer projetos sozinho, beleza!

**Comment by tchars** [comment]
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk sai daqui, abener

**Comment by ABNERMATHEUS** [comment]
Vou criar um bot para toda vez que você criar um repositório, abrir um issue
